select * from scm.dbo.[Sheet1$];

 1! total sales YTD
SELECT YEAR,SUM(SALES) AS SALES FROM SCM.DBO.[SHEET1$]
GROUP BY YEAR;

1!! total sales MTD
SELECT MONTH,SUM(SALES) AS SALES FROM SCM.DBO.[SHEET1$]
GROUP BY MONTH;


1!!! total sales QTD
SELECT QUARTER,SUM(SALES) AS SALES FROM SCM.DBO.[SHEET1$]
GROUP BY QUARTER;

2 Product type wise sales
SELECT 
    PRODUCT_TYPE AS PRODUCTS,
    CONCAT(FORMAT(SUM(SALES) / 1000000, 'N2'), 'M') AS TOTAL_SALES
FROM SCM.DBO.[SHEET1$]
GROUP BY PRODUCT_TYPE
ORDER BY PRODUCTS;

3 sales growth
SELECT YEAR,CONCAT(FORMAT(SUM(SALES)/1000000,'N2'), 'M') AS TOTAL_SALES
FROM SCM.DBO.[SHEET1$]
GROUP BY YEAR
ORDER BY YEAR;

4 state wise sales
SELECT STORE_STATE AS STATE,
      CONCAT(FORMAT(SUM(SALES)/1000000,'N2'), 'M') as TOTAL_SALES 
FROM SCM.DBO.[SHEET1$]
GROUP BY STORE_STATE;

5 region wise sales 
 SELECT STORE_REGION AS REGION,
      CONCAT(ROUND(SUM(SALES)/1000000, 2), 'M') AS TOTAL_SALES
FROM SCM.DBO.[SHEET1$]
GROUP BY STORE_REGION
ORDER BY SUM(SALES) DESC;

6 top 5 stores wise sales
 SELECT TOP 5 
    STORE_NAME, 
    SUM(SALES) AS TOTAL_SALES
FROM SCM.DBO.[SHEET1$]
GROUP BY STORE_NAME
ORDER BY TOTAL_SALES DESC;

7 total SALES
SELECT CONCAT(ROUND(SUM(SALES)/1000000,2),'M') AS TOTAL_SALES
FROM  SCM.DBO.[SHEET1$];

8 total inventory
SELECT concat(round(sum(Inventory_Value)/1000000,2),'M') AS Total_Inventory
FROM SCM.DBO.[SHEET1$];

9 purchase method wise sales
SELECT PURCHASE_METHOD,
    CONCAT(ROUND(SUM(SALES)/1000000, 2), 'M') AS TOTAL_SALES
FROM SCM.DBO.[SHEET1$]
WHERE PURCHASE_METHOD IS NOT NULL
GROUP BY PURCHASE_METHOD
 ORDER BY SUM(SALES)DESC;

